Fix heuristics bug: undefined check_y variable
BUGFIX: Fixed UnboundLocalError in is_safe_position

The variable check_y was used before being defined in line 41.
Changed to use y (the parameter) instead of undefined check_y.

Error was:
  UnboundLocalError: cannot access local variable 'check_y'
  where it is not associated with a value

Fixed in bomber_game/heuristics.py line 41.